### ISSUE TITLE
Unable to launch on Arch linux due to dependency issue

### ISSUE THREAD

**Issue by skewballfox** [theunraveler/taskwarrior-web#128]
I'm not sure if the issue is with the project or something related to my install, If you need anymore information please request it and I'll add it to the bug report below. When I try to launch task web I get an error related to my a missing dependency which I do have installed. 

Steps to reproduce:

    1.launch task-web from zsh shell

Output of task --version:
`2.5.1`

output of task-web:
```
Traceback (most recent call last):
	12: from /usr/bin/task-web:23:in `<main>'
	11: from /usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	10: from /usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	 9: from /usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 7: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 6: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 5: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 3: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 2: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 1: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'rack-protection' (= 2.0.5) - did find: [rack-protection-2.0.3] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/daedalus/.gem/ruby/2.6.0:/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
```

**Comment by paanvaannd** [comment]
Perhaps this is related to sinatra/sinatra#1149, since Sinatra is a dependency of Taskwarrior Web?

Try:

```
gem "rack-protection", :github => "sinatra/rack-protection"
```

as suggested in the linked issue and see if that helps.

**Comment by Zebradil** [comment]
What about running it with [docker](https://github.com/theunraveler/taskwarrior-web#docker)?
