### ISSUE TITLE
task-web does not work in macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by mgiugliano** [theunraveler/taskwarrior-web#147]
Following the official or unofficial (see issue #144) install instructions, launching task-web fails returning a series of errors:

```
Traceback (most recent call last):
	17: from /Users/MY/.gem/ruby/2.7.0/bin/task-web:23:in `<main>'
	16: from /Users/MY/.gem/ruby/2.7.0/bin/task-web:23:in `load'
	15: from /Users/MY/.gem/ruby/2.7.0/gems/taskwarrior-web-1.1.12/bin/task-web:6:in `<top (required)>'
	14: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	13: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	12: from /Users/MY/.gem/ruby/2.7.0/gems/taskwarrior-web-1.1.12/lib/taskwarrior-web.rb:5:in `<top (required)>'
	11: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:1:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:1:in `each'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	 6: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
	 3: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object/duplicable.rb:109:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
```

```
> gem --version
3.1.2

> ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

**Comment by osleg** [comment]
The problem is in third party library `activesupport` and ruby 2.7
If you downgrade to ruby<2.7 it'll work

**Comment by mgiugliano** [comment]
Same problem under Big Sur, as I had forgotten your earlier advice!!! I am sadly unable to use task-web as I can't downgrade ruby. :-(
