### ISSUE TITLE
task-web won't start with newest ruby version

### ISSUE THREAD

**Issue by Pupo1** [theunraveler/taskwarrior-web#156]
I installed  taskwarrior-web on my desktop computer and it works fine - i have ruby 2.5.5p157 , Debian 10

So I wanted to give it a go on my server, with ruby 2.7.4p191 on Debian 11, and I get: 

```
Traceback (most recent call last):
        17: from /usr/local/bin/task-web:23:in `<main>'
        16: from /usr/local/bin/task-web:23:in `load'
        15: from /var/lib/gems/2.7.0/gems/taskwarrior-web-1.1.12/bin/task-web:6:in `<top (required)>'
        14: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        13: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        12: from /var/lib/gems/2.7.0/gems/taskwarrior-web-1.1.12/lib/taskwarrior-web.rb:5:in `<top (required)>'
        11: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        10: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         9: from /var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:1:in `<top (required)>'
         8: from /var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:1:in `each'
         7: from /var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
         6: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         5: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         4: from /var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         2: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         1: from /var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object/duplicable.rb:109:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)

```

**Comment by VeniVidiVinzi** [comment]
Hey there, 
it seems that the taskwarrior-web gem is not compatible with the latest version of Ruby (2.7.x) and Debian 11.

I faced a similar problem on Linux Mint and was able to solve it by downgrading both Ruby and gem to version 2.5. To install taskwarrior-web on my server, I used the following command:

```bash
sudo /usr/bin/gem2.5 install taskwarrior-web
```
This allowed me to use taskwarrior-web without any issues on my server.
I Hope this helps.

**Comment by Pupo1** [comment]
Thanks a lot for the hint. But shouldn't it be a general security issue to downgrade any program?  I don't want to be hacked if there should be a vulnerability in ruby 2.5 which would have been fixed in ruby 2.7 or later.

**Comment by xgpt** [comment]
This seems like a strong argument for packaging this application up in a container like Docker isn't it? It could even be hosted by the GitHub registry for free I believe.

**Comment by Pupo1** [comment]
> yes, I would prefer that, too.
