### ISSUE TITLE
Clean install from gems throws error when surfing it

### ISSUE THREAD

**Issue by matthiasbeyer** [theunraveler/taskwarrior-web#62]
Hi.

I installed taskwarrior (`apt-get install task`) and taskwarrior-web (`gem install taskwarrior-web`) and pasted `task-web.user=foo` and `task-web.passwd=bar` to `.taskrc`.

Then I surfed to `<ip>:5678` and got:

```
Versionomy::Errors::ParseError - Extra characters: "\nConfiguration override rc.xterm.title:no\nConfiguration override rc.color:off\nConfiguration override rc.verbose:no\nConfiguration override rc.confirmation:no":
        /var/lib/gems/1.9.1/gems/versionomy-0.4.4/lib/versionomy/format/delimiter.rb:199:in `parse'
        /var/lib/gems/1.9.1/gems/versionomy-0.4.4/lib/versionomy/interface.rb:130:in `parse'
        /var/lib/gems/1.9.1/gems/taskwarrior-web-1.1.11/lib/taskwarrior-web/model/config.rb:44:in `version'
        /var/lib/gems/1.9.1/gems/taskwarrior-web-1.1.11/lib/taskwarrior-web/model/config.rb:68:in `supports?'
        /var/lib/gems/1.9.1/gems/taskwarrior-web-1.1.11/lib/taskwarrior-web/app.rb:30:in `block in <class:App>'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `[]'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `block in filter!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `each'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `filter!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1075:in `block in dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
        /var/lib/gems/1.9.1/gems/rack-flash3-1.0.5/lib/rack/flash.rb:124:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
192.168.200.97 - - [22/Apr/2014:22:21:52 CEST] "GET / HTTP/1.1" 500 146341
- -> /
```

**Comment by Zebradil** [comment]
Taskwarrior-web requires Taskwarrior to be installed and accessible through `task` command. Non-standard configuration is not required. For further reference see [official tasked docs](https://taskwarrior.org/docs/taskserver/setup.html).
