### ISSUE TITLE
LoadError while setting up task-web on raspberry pi

### ISSUE THREAD

**Issue by qitta** [theunraveler/taskwarrior-web#67]
Hi,

I am getting the following error while starting task-web on raspberry pi:

```
[katze@alarmpi ~]$ task-web                                                                                                                                                                                         
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n/core_ext/string/interpolate (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/katze/.gem/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext/string/interpolation.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/katze/.gem/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext/string.rb:9:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/katze/.gem/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /home/katze/.gem/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `each'
        from /home/katze/.gem/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/katze/.gem/ruby/2.1.0/gems/taskwarrior-web-1.1.11/lib/taskwarrior-web.rb:5:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/katze/.gem/ruby/2.1.0/gems/taskwarrior-web-1.1.11/bin/task-web:6:in `<top (required)>'
        from /home/katze/.gem/ruby/2.1.0/bin/task-web:23:in `load'
        from /home/katze/.gem/ruby/2.1.0/bin/task-web:23:in `<main>'
```

System:
- Archlinux ARM, Linux 3.12.24-1-ARCH, armv6l GNU/Linux
- Ruby 2.1.2p95 (2014-05-08 revision 45877) [armv6l-linux-eabihf]
- Taskwarrior 2.3.0

Is something missing? Is task-web known to work on the raspberry pi?

Many tanks,

Christoph

**Comment by derekslenk** [comment]
@qitta did you have time to try @pschmitt's idea?

**Comment by qitta** [comment]
@derekslenk, sorry but I cannot confirm this, as I don't have this system setup (Raspberry Pi + Arch Linux) running anymore. 

As for me, we can just close this issue.
