### ISSUE TITLE
OpenURI::HTTPError

### ISSUE THREAD

**Issue by jajadvert** [theunraveler/taskwarrior-web#68]
I don't know what's wrong here.
But when starting task-web I get this error:

[2014-11-03 13:42:35 +0100] Starting 'taskwarrior-web'...
[2014-11-03 13:42:35 +0100] trying port 5678...
/usr/lib/ruby/2.1.0/open-uri.rb:353:in `open_http': 503 Service Unavailable (OpenURI::HTTPError)
    from /usr/lib/ruby/2.1.0/open-uri.rb:724:in`buffer_open'
    from /usr/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
    from /usr/lib/ruby/2.1.0/open-uri.rb:208:in`catch'
    from /usr/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
    from /usr/lib/ruby/2.1.0/open-uri.rb:149:in`open_uri'
    from /usr/lib/ruby/2.1.0/open-uri.rb:704:in `open'
    from /usr/lib/ruby/2.1.0/open-uri.rb:34:in`open'
    from /var/lib/gems/2.1.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `port_open?'
    from /var/lib/gems/2.1.0/gems/vegas-0.1.11/lib/vegas/runner.rb:132:in`find_port'
    from /var/lib/gems/2.1.0/gems/vegas-0.1.11/lib/vegas/runner.rb:109:in `start'
    from /var/lib/gems/2.1.0/gems/vegas-0.1.11/lib/vegas/runner.rb:77:in`initialize'
    from /var/lib/gems/2.1.0/gems/taskwarrior-web-1.1.11/bin/task-web:9:in `new'
    from /var/lib/gems/2.1.0/gems/taskwarrior-web-1.1.11/bin/task-web:9:in`<top (required)>'
    from /usr/local/bin/task-web:23:in `load'
    from /usr/local/bin/task-web:23:in`<main>'

**Comment by claf** [comment]
exact same error on ubuntu 16.04 with a fresh taskwarrior-web install using gem

**Comment by MartyLake** [comment]
Same there !

**Comment by X3MBoy** [comment]
Some here on Fedora 31
