### ISSUE TITLE
http.rb:763:in `initialize': Invalid argument - connect(2) (Errno::EINVAL)

### ISSUE THREAD

**Issue by doroseracledes** [theunraveler/taskwarrior-web#75]
I installed task-web on OpenBSD 5.7 without any issues using gem install task-web:

Successfully installed vegas-0.1.11
Successfully installed rinku-1.7.3
Successfully installed blockenspiel-0.4.5
Successfully installed versionomy-0.4.4
Successfully installed i18n-0.7.0
Successfully installed multi_json-1.11.2
Successfully installed activesupport-3.2.22
Successfully installed simple-navigation-4.0.3
Successfully installed sinatra-simple-navigation-4.0.0
Successfully installed rack-flash3-1.0.5
Successfully installed json-1.7.7
Successfully installed taskwarrior-web-1.1.11
17 gems installed

But when I try starting task-web I get this error:

~$ task-web19                                                 
[2015-08-28 16:12:21 +0300] Starting 'taskwarrior-web'...
[2015-08-28 16:12:21 +0300] trying port 5678...
/usr/local/lib/ruby/1.9.1/net/http.rb:763:in `initialize': Invalid argument - connect(2) (Errno::EINVAL)
        from /usr/local/lib/ruby/1.9.1/net/http.rb:763:in `open'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
        from /usr/local/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
        from /usr/local/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:763:in `connect'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:745:in `start'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:776:in `buffer_open'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:678:in `open'
        from /usr/local/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from /home/deracled/.gem/ruby/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `port_open?'
        from /home/deracled/.gem/ruby/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:132:in `find_port'
        from /home/deracled/.gem/ruby/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:109:in `start'
        from /home/deracled/.gem/ruby/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:77:in `initialize'
        from /home/deracled/.gem/ruby/1.9.1/gems/taskwarrior-web-1.1.11/bin/task-web:9:in `new'
        from /home/deracled/.gem/ruby/1.9.1/gems/taskwarrior-web-1.1.11/bin/task-web:9:in `<top (required)>'
        from /home/deracled/.gem/ruby/1.9.1/bin/task-web19:23:in `load'
        from /home/deracled/.gem/ruby/1.9.1/bin/task-web19:23:in `<main>'
--------------------------------------------------------------------------------------

my taskwarror version is:

$ task _version
2.4.0

**Comment by doroseracledes** [comment]
not using any longer
