### ISSUE TITLE
task-web not running

### ISSUE THREAD

**Issue by unfa** [theunraveler/taskwarrior-web#89]
I downloaded task-web, extracted the archive and tried to run it. I got this:

```
unfa@unfa-Latitude-3550 ~/Downloads/theunraveler-taskwarrior-web-33ce5da/bin $ ./task-web 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/core_ext (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/unfa/Downloads/theunraveler-taskwarrior-web-33ce5da/lib/taskwarrior-web.rb:5:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./task-web:6:in `<main>'
```

**Comment by Zebradil** [comment]
Closing the issue until new details.
