### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by blastmaster** [theunraveler/taskwarrior-web#91]
Hi,
can you provide more detailed installation instruction please?
I've the following issue, I'am running on a debian sid distribution.
When following the instructions on your website for installation:
```
sudo gem install taskwarrior-web
```
Everything get installed.
But when trying to launch ```task-web``` I get the following Error:
```
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/number_helper.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/numeric.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext.rb:3:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext.rb:2:in `each'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/taskwarrior-web-1.1.12/lib/taskwarrior-web.rb:5:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/taskwarrior-web-1.1.12/bin/task-web:6:in `<top (required)>'
        from /usr/local/bin/task-web:22:in `load'
        from /usr/local/bin/task-web:22:in `<main>'
```
Can you help?

**Comment by Zebradil** [comment]
You have wrong version of activesupport. [Taskwarrior-web supports version 3](https://github.com/theunraveler/taskwarrior-web/blob/master/taskwarrior-web.gemspec#L25).

**Comment by irl** [comment]
Debian sid has 4.2.9 (+ debian patches).

Any chance that taskwarrior-web will support version 4?

**Comment by michaelgold** [comment]
I had the same issue. 
`gem list` showed two versions of activesupport installed
`activesupport (5.1.4, 3.2.22.5)`

I ran `sudo gem uninstall activesupport` and was able to choose to uninstall version 5.1.4.
